name: Run all tests

on: [push, pull_request]
jobs:
  # paths:
  #   - "src/*"
  #   - ".github/workflows/*.yml"
  #   - "Dockerfile"
  #   - ".dockerignore"
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, test and test build
        run: |
          docker-compose up -d postgres
          npm ci --quiet
          npm test
          npm run build --if-present
        env:
          CI: true
          AWS_BUCKET_DEV: test
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_REQ_URL: ${{ secrets.AUTH0_REQ_URL }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
