version: "3"

services:
  flusshygiene-opencpu-base:
    container_name: flusshygiene-opencpu-base
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8004:8004
    env_file: ./.env
